# Generated by Django 3.1.2 on 2020-10-17 06:31

from django.db import migrations, models
import django.db.models.deletion
import items.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'db_table': 'inventory',
                'ordering': ['store'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[items.validators.price_validator])),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'item',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('location', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'store',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryHasItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.PositiveSmallIntegerField(default=0)),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.inventory')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'db_table': 'inv_has_item',
                'ordering': ['items'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='has_item',
            field=models.ManyToManyField(through='items.InventoryHasItem', to='items.Item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.store'),
        ),
    ]
